version: '3.8'
services:
  iqt:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"  # Debug port
    volumes:
      - .:/app
    environment:
      - FLASK_APP=IQT.py
      - FLASK_ENV=development
    command: python -m debugpy --listen 0.0.0.0:5678 -m flask run --host 0.0.0.0 --port 5000 --no-debugger --no-reload